import type { Metadata } from "next";
import "./globals.css";

import { geistMono, geistSans } from "../config/fonts";

export const metadata: Metadata = {
  title: "Mi aplicacion next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
